global:
  slack_api_url: 'https://hooks.slack.com/services/TTTTTTTTT/BBBBBBB/AAAAAAAAAAAAA'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alexandr'
